_extends: .github:.github/_opensource.yml

repository:
  name: gcloud-configuration-ohmyzsh-plugin
  description: A simple oh-my-zsh plugin to display the active gcloud configuration
  topics: ohmyzsh, gcloud
  is_template: false
  delete_branch_on_merge: true
